config/routes.rb
Rails.application.routes.draw do
  root 'party#index'
  post 'party/reasons' => 'party#reasons', as: :reasons
  get 'party' => 'party#view', as: :view
end

app/models/cheerup.rb
class Cheerup < ActiveRecord::Base
  has_and_belongs_to_many :reasons
end

app/models/party_planner.rb
class PartyPlanner
  def initialize(id_array)
    @ids = id_array
    @reasons = []
    @cheerups_array = []
  end

  def invite_cheerups
    convert_ids_format
    interpret_reasons
    find_cheerups
  end

  private
    def convert_ids_format
      @ids.map! {|id| id.to_i}
    end

    def interpret_reasons
      @ids.each do |id|
        reason_object = Reason.find(id)
        @reasons << reason_object
      end
    end

    def find_cheerups
      @reasons.each do |reason|
        reason.cheerups.each do |cheerup|
          @cheerups_array << cheerup.visual_source
        end
      end
      @cheerups_array
    end

end

app/models/reason.rb
class Reason < ActiveRecord::Base
  has_and_belongs_to_many :cheerups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/party_controller.rb
class PartyController < ApplicationController
  def index
    @reasons = Reason.all
  end

  def view
    # @cheerups_array = PartyPlanner.new(params[:reason_ids]).invite_cheerups

    respond_to do |format|
        format.json { render :json => {:cheerups_response => PartyPlanner.new(params[:reason_ids]).invite_cheerups} }
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PitypartyMe</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script src="http://documentcloud.github.com/underscore/underscore-min.js"></script>
  <script src="http://documentcloud.github.com/backbone/backbone-min.js"></script>
</body>
</html>

app/views/party/index.html.erb
<div class="pity_party">
    <div class="container">
      <div class="request-container">
        <h1> FUQQQ ITTT</h1>
        <%= form_tag(view_path, :method => "post", remote: true) do %>
        <ul style="list-style-type:none;">
        <% @reasons.each do |t| %>
            <li> <%= check_box_tag  "reason_ids[]",t.id %> <%= t.name %>  </li>
        <%end%>
        </ul>
        <%= submit_tag("Pity Party Begin", :class => "doit") %>
        <%end %>
      </div>

    </div>

    <h1>Form Via Backbone</h1>
    <table class="reasons_table">
        <tr>
            <th>Name</th>
        </tr>
    </table>

</div>

<script type="text/javascript">
    $(function() {
        App.init();
    });
</script>

app/views/party/view.html.erb
<h1> Cheer Up </h1>

<% @cheerups_array.each do |cheerup| %>
  <img src=<%=cheerup%>/>
<%end%>